name: Build and Release Startset

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build Startset
      run: |
        go mod tidy
        go build -o startset.exe main.go

    # Generate a version based on the current date in YYYY.MM.DD format
    - name: Set Release Version
      id: set_version
      run: echo "RELEASE_VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    # Create a release and upload the binary as an asset
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.RELEASE_VERSION }}  # Use the generated version
        release_name: "Startset v${{ env.RELEASE_VERSION }}"
        body: "Release notes or changes in this version."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Binary to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: startset.exe
        asset_name: startset.exe
        asset_content_type: application/octet-stream
