name: Build Startset

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 for compatibility with Node.js 20

    - name: Set up Go
      uses: actions/setup-go@v4  # Updated to v4 for compatibility with Node.js 20
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3  # Updated to v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build Startset
      run: |
        go mod tidy  # Ensure all dependencies are up-to-date
        go build -o startset.exe main.go

    - name: Upload Binary
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: startset-exe
        path: startset.exe
